### PR TITLE
fix issue #52

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
removed all the config about the homeassistant_ip.
IP is set now via `get_local_ip()`

This should work if you don't have docker network isolation. This is taken from the homekit guide:

> Docker Network Isolation
> 
> The advertise_ip option can be used to run this integration even inside an ephemeral Docker container with network isolation enabled, e.g., not using the host network.
> 
> To use advertise_ip, add the option to your homekit config:
> 
> homekit:
>   advertise_ip: "STATIC_IP_OF_YOUR_DOCKER_HOST"
> YAMLCopy
> Restart your Home Assistant instance. This feature requires running an mDNS forwarder on your Docker host, e.g., avahi-daemon in reflector mode. This kind of setup most likely requires safe_mode during the bridge setup.

Therefore another way would be to keep homeassistant_ip (just like homekit does). In that case I would suggest to keep it only in case of configuration.yaml (to make the config flow as simple as possible). However, as Hassio and venv works without such an advertise_ip I would suggest to keep it as simple as in this PR.

### CODE REVIEW

**Comment by mammuth** [comment]
> However, as Hassio and venv works without such an advertise_ip I would suggest to keep it as simple as in this PR.

👍

**Comment by mammuth** [comment]
@AaronDavidSchneider I think it makes sense that you rebase/merge master; I had a quick look but was afraid to make merge mistakes with the multistep config, so you would have needed to review the merge anyways.

**Comment by AaronDavidSchneider** [comment]
Needs to be extended since latest merge of config_flow opt

**Comment by AaronDavidSchneider** [comment]
works for me now. Please verify @mammuth 
PS: also changed some strings in config flow.

**Comment by mammuth** [comment]
Works.

**Pull request merged**
