### PR TITLE
Use async tasks for sync function calls to fritzconnection 

### LINKED ISSUE #82: I/O inside the eventloop
Hallo,

@Krocko told me about warnings in Homeassistant 0.109.0 beta.

```
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 23:24:20 (270 occurrences) 
Last logged: 23:33:37

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 222: info = self.connection.call_action("DeviceInfo:1", "GetInfo")
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/switch.py, line 622: f"WLANConfiguration:{self._network_num}", "GetInfo"
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/switch.py, line 347: self.fritzbox_tools.connection.call_action("X_AVM-DE_OnTel:1", "GetDeflections")["NewDeflectionList"]
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/binary_sensor.py, line 66: self._is_on = status.is_connected
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/binary_sensor.py, line 75: self._attributes[attr] = getattr(status, attr)
```

Looks like, its now necessary to replace all `call_action` calls and everything related to IO by something different.
I don't have the time at the moment. Could you take a look into it @mammuth?

### PR DESCRIPTION
**Pull request by mammuth**
Kind of a hassle to work with a sync library, but it looks like that will also improve the overall performance of the integration! 🎉 

I tested manually:
- [x] Connectivity sensor meta data
- [x] Get/Set port switch
- [x] Get/Set 2.4 Ghz wifi
- [x] Get/Set guest wifi switch
- [x] Get/Set call deflections
- [ ] Yaml Mode

Closes #82

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I am looking and testing it right now. I will try to give feedback asap

**Comment by AaronDavidSchneider** [comment]
I think you are missing the profile_switch.
```
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 1:50:21 PM (31 occurrences) 
Last logged: 1:56:02 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 216: "Layer3Forwarding:1", "GetDefaultConnectionService"
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 200: await asyncio.coroutine(self.profile_switch.fetch_profiles)()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 201: await asyncio.coroutine(self.profile_switch.fetch_devices)()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 202: await asyncio.coroutine(self.profile_switch.fetch_device_profiles)()
```

However, I also got this error:
```
Unable to prepare setup for platform fritzbox_tools.binary_sensor: Platform not found (cannot import name 'BinarySensorEntity' from 'homeassistant.components.binary_sensor' (/Users/schneider/codes/homeassistant/lib/python3.7/site-packages/homeassistant/components/binary_sensor/__init__.py)).
```

**Comment by mammuth** [comment]
> I think you are missing the profile_switch.

Great find. The profile switch itself already was async, but I forgot `FritzBoxTools.is_ok()` which is called during the config flow creation (that's why I didn't see it anymore, because I didn't re-add the integration).

**Comment by AaronDavidSchneider** [comment]
> I had a warning that the base class of the binary sensor changed, but apparently your HA version doesn't support the new one yet. I'll remove that change (it doesn't belong to the PR anyways).
I am using the newest beta, I think. Home Assistant 0.109.0b2

I am now still getting these errors:
```
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 2:08:12 PM (6 occurrences) 
Last logged: 2:09:56 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 200: await asyncio.coroutine(self.profile_switch.fetch_profiles)()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 201: await asyncio.coroutine(self.profile_switch.fetch_devices)()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for fritzbox_tools doing I/O at custom_components/fritzbox_tools/__init__.py, line 202: await asyncio.coroutine(self.profile_switch.fetch_device_profiles)()
```

**Comment by mammuth** [comment]
Doc: the last commit broke something (because of the nested asyncio calls probably). Need to follow-up on that.

Nevertheless, the setting of the profile switch state is not working reliably. Looks like it doesn't set the state on the router as long as it's in our "grace period" (where it doesn't refresh the state because a toggle just happened). No clue whether that's a new issue or not.

**Comment by AaronDavidSchneider** [comment]
> Doc: the last commit broke something (because of the nested asyncio calls probably). Need to follow-up on that.
> 
> Nevertheless, the setting of the profile switch state is not working reliably. Looks like it doesn't set the state on the router as long as it's in our "grace period" (where it doesn't refresh the state because a toggle just happened). No clue whether that's a new issue or not.

I get this Log message:
```
2020-04-25 14:31:54 INFO (SyncWorker_22) [root] 
UPDATING DEVICE PROFILES...
2020-04-25 14:31:54 INFO (SyncWorker_22) [root]   CHANGING PROFILE OF landevice1510561/Aarons-iPhone TO filtprof9999/Gesperrt
2020-04-25 14:31:57 DEBUG (MainThread) [custom_components.fritzbox_tools.switch] Not updating switch state, because last toggle happend < 30 seconds ago
```

Looks like your right...

**Comment by AaronDavidSchneider** [comment]
I think we need to move `async def async_update_profiles(self):` from `FritzBoxTools` to switch.py (into class `FritzBoxProfileSwitch`). 
The disadvantage: async_update_profiles will be called from every switch (can be many, but arent probably).

**Comment by mammuth** [comment]
> Nevertheless, the setting of the profile switch state is not working reliably. Looks like it doesn't set the state on the router as long as it's in our "grace period" (where it doesn't refresh the state because a toggle just happened). No clue whether that's a new issue or not.

This issue is also present on current `master`. So I guess it's fine to not handle it within this PR.

**Pull request merged**
