### PR TITLE
Rename entity class names to reduce warnings

### PR DESCRIPTION
**Pull request by N1c093**
Change entity class names to reduce warnings with HA Version 0.110

This is my first pull request. Hopefully I did everything right :)

I tested (as appropriate):
- [ ] Get/Set port switch
- [X] Get/Set 2.4 Ghz wifi
- [X] Get/Set 5 Ghz wifi
- [X] Get/Set guest wifi switch
- [ ] Get/Set call deflections
- [X] Connectivity sensor
- [ ] Yaml Mode

Closes issue #87

### CODE REVIEW

**Comment by mammuth** [comment]
Thanks for your contribution! :tada: It's highly appreciated!

If we update this, there is a version of HA that we don't support anymore. Do you know what's the latest version we can support after this change?

Then I'll probably add a warning to a) the info page within hacs and b) as part of the release notes

**Comment by N1c093** [comment]
I think 0.110 is the first version which supports it. So everything under 0.110 would be unsupported/not working.

You can also implement backwards compatibility, but I'm not that fimilar with programming. Do I just have to modify the import section? If it's that easy I can modify my pull request. https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/

**Comment by N1c093** [comment]
@mammuth just added the backwards compatibility. I've tested it with 0.110 and 0.109.6. So there is no need add a warning at the release notes.

**Comment by mammuth** [comment]
Your import compatibility should be fine :+1:

**Comment by mammuth** [comment]
Merged and released to HACS as `1.9.1` . Thanks :rocket:

**Pull request merged**
