### PR TITLE
optimize config_flow by adding options

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
adds another config step where user can decide which switches should be exposed

- [x] locally tested to work

closes issue #61

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I am not entirely sure if we decided to use Fritz or FRITZ. Now its FRITZ everywhere in the config_flow

**Comment by mammuth** [comment]
Thanks @AaronDavidSchneider!

I see this being useful for a couple (although only few) people. But I'm not quite sure whether this justifies cluttering the config flow. 
It's quite common for integration to create entities for everything it supports. 

TBH the reasoning in the mentioned issue is quite shallow: On larger HA setups, people tend to whitelists what to expose to other cloud services (because otherwise they're useless anyways with dozens of bad named entities), if people are annoyed by too many entities in their UI they probably create their own Lovelace config anyways.

Besides, entities can be disabled via the Integrations UI (not sure whether we automatically support this?).

We're creating the stuff asynchronous, so the startup shouldn't be affected too much. Obviously it takes resources to update the entities, but it's probably not worth mentioning. 

So, the question I want to rise is: Does it really make sense to add complexity to the code and the configuration because a few people want some entities to not be created (because they don't want to use the concepts already present in HA (disabling entities, whitelisting entities for external exposure)).

**Comment by AaronDavidSchneider** [comment]
Thanks for your comment @mammuth!

This PR doesn't clutter the config flow too much! Its at most one simple additional form.
If you don't use device profiles the config flow skips the last step.

Screenshot 2020-02-10 at 12 04 52

I would say its worth it. But you got to decide :D

**Comment by mammuth** [comment]
> This PR doesn't clutter the config flow too much! Its at most one simple additional form.

True, I expected it to be way worse 🙈

**Pull request merged**
